default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hwapi_development

test:
  <<: *default
  database: hwapi_test

production:
  <<: *default
  database: helloworld_production
  url: <%= ENV['DATABASE_URL'] %>
